Bump to python3
pblaas/docker_openstack-cli pull request #2
Opened 2020-04-28 18:14 UTC by blackplane

Hi, openstack-cli didn't work and bumping it to python3 did the trick. Not sure about the implications for terraform, etc.

2020-04-28 18:32 UTC, pblaas commented
Hi @blackplane thank you for the PR. Could you elaborate what didn't work for with with openstack-cli? and did you use this container image to connect to CloudVPS Openstack or another Openstack platform?

2020-05-05 23:44 UTC, blackplane commented
Sure, openstack-cli is dropping python 2.7 (e.g., see https://github.com/openstack/python-openstackclient/commit/f01a0f336c497584cc38e4396ee87282bdef1f5c)

I've used the container to access our own OpenStack instance.

2020-05-07 08:21 UTC, pblaas requested changes
Tested the python changes and look good to me! 
Except for the reference to the docker container in the cli command which is pointing to your container instead of mine.

2020-05-07 08:21 UTC, pblaas commented on openstack-cli.sh
> +	blackplane/openstack-cli:latest
I can't accept this change, please revert it back.
```suggestion
	docker.io/pblaas/openstack-cli:latest
```

2020-05-12 13:16 UTC, merged